# Site settings

title: BLOG
description: >-
  Personal blog
url: "https://phyacms.me"
baseurl: "/"

theme: "phyacms-theme"
github: [metadata]

owner: "Myeungsang Cho"
username: phyacms
email: phyacms@gmail.com
github_username: phyacms

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
